// Generated by sva2rtl 0.1.0
// Source: test.sv:3:5
// Original property: @(posedge clk) (a && b)
module sva_my_check (
    input  logic clk,
    input  logic rst_n,
    input  logic start,
    input  logic a,
    input  logic b,
    output logic active,
    output logic pass,
    output logic fail,
    output logic attempt_fired
);

    // ── Combinational evaluation ───────────────────────────────────────
    logic bool_result;
    assign bool_result = ((a && b));

    // ── Registered outputs (OUT-02: no combinational glitches) ─────────
    logic active_q, pass_q, fail_q, attempt_fired_q;
    always_ff @(posedge clk) begin
        if (!rst_n) begin
            active_q        <= 1'b0;
            pass_q          <= 1'b0;
            fail_q          <= 1'b0;
            attempt_fired_q <= 1'b0;
        end else begin
            active_q        <= start;
            pass_q          <= start &  bool_result;
            fail_q          <= start & ~bool_result;
            attempt_fired_q <= attempt_fired_q | start;  // sticky
        end
    end

    assign active        = active_q;
    assign pass          = pass_q;
    assign fail          = fail_q;
    assign attempt_fired = attempt_fired_q;

endmodule
