// Generated by sva2rtl 0.1.0
// Source: impl_overlap.sv:2:14
// Original property: @(posedge clk) a |-> b
module sva_impl_check #(
    parameter BV_WIDTH = 1
) (
    input  logic clk,
    input  logic rst_n,
    input  logic start,
    input  logic a,
    input  logic b,
    input  logic disable_i,
    output logic active,
    output logic pass,
    output logic fail,
    output logic attempt_fired,
    output logic overflow_flag,
    output logic disabled_o
);
    // ── Internal wires from child modules ────────────────────────────────────
    logic ant_pass_w;
    logic ant_active_w;
    logic ant_fail_w;
    logic ant_afired_w;
    logic con_pass_w;
    logic con_active_w;
    logic con_fail_w;
    logic con_afired_w;

    // ── Consequent start: driven from bit-vector oldest thread ────────────────
    logic con_start_w;
    assign con_start_w = bv_q[BV_WIDTH-1];

    // ── Antecedent child instantiation ───────────────────────────────────────
    sva_prop_47ec2b81 u_sva_prop_47ec2b81 (
        .clk(clk),
        .rst_n    (rst_n),
        .start    (start),
        .a(a),
        .disable_i     (disable_i),
        .active        (ant_active_w),
        .pass          (ant_pass_w),
        .fail          (ant_fail_w),
        .attempt_fired (ant_afired_w),
        .disabled_o    ()
    );

    // ── Consequent child instantiation ───────────────────────────────────────
    sva_prop_47ec2b81 u_sva_prop_47ec2b81 (
        .clk(clk),
        .rst_n    (rst_n),
        .start    (con_start_w),
        .b(b),
        .disable_i     (disable_i),
        .active        (con_active_w),
        .pass          (con_pass_w),
        .fail          (con_fail_w),
        .attempt_fired (con_afired_w),
        .disabled_o    ()
    );

    // ── Bit-vector shift register (thread tracker) ────────────────────────────
    // Each bit position represents a thread started N cycles ago.
    // bit[0] = thread started this cycle; shift right = all threads age.
    logic [BV_WIDTH-1:0] bv_q;
    logic                overflow_flag_q;
    logic                attempt_fired_q;

    // Overflow: antecedent fires while all bit positions occupied
    logic overflow_event;
    assign overflow_event = ant_pass_w && (&bv_q) && !overflow_flag_q;

    always_ff @(posedge clk) begin
        if (!rst_n || disable_i) begin
            bv_q            <= '0;
            overflow_flag_q <= 1'b0;
            attempt_fired_q <= 1'b0;
        end else begin
            attempt_fired_q <= attempt_fired_q | ant_pass_w;  // sticky
            if (overflow_flag_q) begin
                // HARD HALT: freeze bv_q, only rst_n clears
                bv_q            <= bv_q;
                overflow_flag_q <= 1'b1;
            end else begin
                overflow_flag_q <= overflow_flag_q | overflow_event;
                // Shift right (all threads age by 1), insert new thread at MSB
                bv_q <= {ant_pass_w, bv_q[BV_WIDTH-1:1]};
            end
        end
    end

    // ── Output assignments ────────────────────────────────────────────────────
    // When disabled, gate active/pass/fail to 0; overflow_flag remains sticky
    assign active        = disable_i ? 1'b0 : (overflow_flag_q ? 1'b0 : (ant_active_w | con_active_w | (|bv_q)));
    assign pass          = disable_i ? 1'b0 : (overflow_flag_q ? 1'b0 : (bv_q[BV_WIDTH-1] & con_pass_w));
    assign fail          = disable_i ? 1'b0 : (overflow_event  ? 1'b1 :
                           overflow_flag_q ? 1'b0 :
                           (bv_q[BV_WIDTH-1] & ~con_pass_w & con_start_w));
    assign attempt_fired = attempt_fired_q;
    assign overflow_flag = overflow_flag_q;
    assign disabled_o    = disable_i;

endmodule
