// Generated by sva2rtl 0.1.0
// Source: delay_zero.sv:2:3
// Original property: @(posedge clk) a ##0 b
module sva_prop_75080d6b (
    input  logic clk,
    input  logic rst_n,
    input  logic start,
    input  logic a,
    input  logic b,
    output logic active,
    output logic pass,
    output logic fail,
    output logic attempt_fired
);
    // ── Internal token wires (N+1 wires for N children) ─────────────────────
    logic w_pass_0;
    logic w_active_0;
    logic w_fail_0;
    logic w_afired_0;
    logic w_pass_1;
    logic w_active_1;
    logic w_fail_1;
    logic w_afired_1;
    logic w_pass_2;
    logic w_active_2;
    logic w_fail_2;
    logic w_afired_2;

    // ── Child module instantiations (token-passing chain) ────────────────────
    sva_prop_75080d6b_e0 u_sva_prop_75080d6b_e0 (
        .clk(clk),
        .rst_n    (rst_n),
        .start    (start),
        .a(a),
        .active        (w_active_0),
        .pass          (w_pass_0),
        .fail          (w_fail_0),
        .attempt_fired (w_afired_0)
    );
    sva_delay_0_0 u_sva_delay_0_0 (
        .clk(clk),
        .rst_n    (rst_n),
        .start    (w_pass_0),
        .active        (w_active_1),
        .pass          (w_pass_1),
        .fail          (w_fail_1),
        .attempt_fired (w_afired_1)
    );
    sva_prop_75080d6b_e1 u_sva_prop_75080d6b_e1 (
        .clk(clk),
        .rst_n    (rst_n),
        .start    (w_pass_1),
        .b(b),
        .active        (w_active_2),
        .pass          (w_pass_2),
        .fail          (w_fail_2),
        .attempt_fired (w_afired_2)
    );

    // ── Top-level output aggregation ─────────────────────────────────────────
    // active: any child is active
    assign active = w_active_0 | w_active_1 | w_active_2;
    // pass: final child's pass output
    assign pass   = w_pass_2;
    // fail: any child signals fail
    assign fail   = w_fail_0 | w_fail_1 | w_fail_2;
    // attempt_fired: first child's attempt_fired (start of sequence)
    assign attempt_fired = w_afired_0;

endmodule
