// Generated by sva2rtl 0.1.0
// Source: delay_zero.sv:2:3
// Original property: @(posedge clk) ##0
module sva_delay_0_0 #(
    parameter CNT_WIDTH = 1
) (
    input  logic clk,
    input  logic rst_n,
    input  logic start,
    output logic active,
    output logic pass,
    output logic fail,
    output logic attempt_fired
);
    // ── ##0 combinational pass-through ──────────────────────────────────────
    assign pass   = start;
    assign active = start;
    assign fail   = 1'b0;

    // ── attempt_fired: sticky, cleared only by rst_n ────────────────────────
    logic attempt_fired_q;
    always_ff @(posedge clk) begin
        if (!rst_n)
            attempt_fired_q <= 1'b0;
        else
            attempt_fired_q <= attempt_fired_q | start;  // sticky
    end
    assign attempt_fired = attempt_fired_q;
endmodule
