// Generated by sva2rtl 1.3.1
// Source: first_match.sv:2:44
// Original property: @(posedge clk) first_match(a ##1 b)
module sva_prop_afd80e6b_body_e0 (
input  logic clk,
input  logic rst_n,
input  logic start,
input  logic a,
input  logic disable_i,
output  logic active,
output  logic pass,
output  logic fail,
output  logic attempt_fired,
output  logic disabled_o
);

    // ── Combinational evaluation ───────────────────────────────────────
    logic bool_result;
    assign bool_result = (a);

    // ── Registered outputs (OUT-02: no combinational glitches) ─────────
    logic active_q, pass_q, fail_q;

always_ff @(posedge clk) begin
        if (!rst_n || disable_i) begin
            active_q <= 1'b0;
            pass_q   <= 1'b0;
            fail_q   <= 1'b0;
        end else begin
            active_q <= start;
            pass_q   <= start &  bool_result;
            fail_q   <= start & ~bool_result;
        end
    end

    // ── HARDEN-01: attempt_fired_q never cleared by disable_i ──────────
    logic attempt_fired_q;

always_ff @(posedge clk) begin
        if (!rst_n) begin
            attempt_fired_q <= '0;
        end else if (start) begin
            attempt_fired_q <= 1'b1;  // sticky — never cleared by disable_i (HARDEN-01)
        end
    end

    assign active        = disable_i ? 1'b0 : active_q;
    assign pass          = disable_i ? 1'b0 : pass_q;
    assign fail          = disable_i ? 1'b0 : fail_q;
    assign attempt_fired = attempt_fired_q;
    assign disabled_o    = disable_i;

endmodule

// Generated by sva2rtl 1.3.1
// Source: first_match.sv:2:44
// Original property: @(posedge clk) ##1
module sva_delay_1_1 #(
    parameter CNT_WIDTH = 1
) (
input  logic clk,
input  logic rst_n,
input  logic start,
input  logic disable_i,
output  logic active,
output  logic pass,
output  logic fail,
output  logic attempt_fired,
output  logic disabled_o
);
    // ── Counter-based delay ──────────────────────────────────────────────────
    logic [CNT_WIDTH-1:0] count_q;
    logic                 running_q;

always_ff @(posedge clk) begin
        if (!rst_n || disable_i) begin
            count_q         <= '0;
            running_q       <= 1'b0;
        end else begin
            if (start) begin
                count_q   <= '0;
                running_q <= 1'b1;
            end else if (running_q) begin
                if (count_q == 1'd1) begin
                    running_q <= 1'b0;
                end else begin
                    count_q <= count_q + 1'b1;
                end
            end
        end
    end

    // ── HARDEN-01: attempt_fired_q never cleared by disable_i ──────────
    logic attempt_fired_q;

always_ff @(posedge clk) begin
        if (!rst_n) begin
            attempt_fired_q <= '0;
        end else if (start) begin
            attempt_fired_q <= 1'b1;  // sticky — never cleared by disable_i (HARDEN-01)
        end
    end

    assign active        = disable_i ? 1'b0 : running_q;
    assign pass          = disable_i ? 1'b0 : (
                               (start && (1 <= 1) && (1 >= 1))
                           );
    assign fail          = 1'b0;
    assign attempt_fired = attempt_fired_q;
    assign disabled_o    = disable_i;
endmodule

// Generated by sva2rtl 1.3.1
// Source: first_match.sv:2:49
// Original property: @(posedge clk) first_match(a ##1 b)
module sva_prop_afd80e6b_body_e1 (
input  logic clk,
input  logic rst_n,
input  logic start,
input  logic b,
input  logic disable_i,
output  logic active,
output  logic pass,
output  logic fail,
output  logic attempt_fired,
output  logic disabled_o
);

    // ── Combinational evaluation ───────────────────────────────────────
    logic bool_result;
    assign bool_result = (b);

    // ── Registered outputs (OUT-02: no combinational glitches) ─────────
    logic active_q, pass_q, fail_q;

always_ff @(posedge clk) begin
        if (!rst_n || disable_i) begin
            active_q <= 1'b0;
            pass_q   <= 1'b0;
            fail_q   <= 1'b0;
        end else begin
            active_q <= start;
            pass_q   <= start &  bool_result;
            fail_q   <= start & ~bool_result;
        end
    end

    // ── HARDEN-01: attempt_fired_q never cleared by disable_i ──────────
    logic attempt_fired_q;

always_ff @(posedge clk) begin
        if (!rst_n) begin
            attempt_fired_q <= '0;
        end else if (start) begin
            attempt_fired_q <= 1'b1;  // sticky — never cleared by disable_i (HARDEN-01)
        end
    end

    assign active        = disable_i ? 1'b0 : active_q;
    assign pass          = disable_i ? 1'b0 : pass_q;
    assign fail          = disable_i ? 1'b0 : fail_q;
    assign attempt_fired = attempt_fired_q;
    assign disabled_o    = disable_i;

endmodule

// Generated by sva2rtl 1.3.1
// Source: first_match.sv:2:44
// Original property: @(posedge clk) first_match(a ##1 b)
module sva_prop_afd80e6b_body (
input  logic clk,
input  logic rst_n,
input  logic start,
input  logic a,
input  logic b,
input  logic disable_i,
output  logic active,
output  logic pass,
output  logic fail,
output  logic attempt_fired,
output  logic disabled_o
);
    // ── Internal token wires (N+1 wires for N children) ─────────────────────
    logic w_pass_0;
    logic w_active_0;
    logic w_fail_0;
    logic w_afired_0;
    logic w_pass_1;
    logic w_active_1;
    logic w_fail_1;
    logic w_afired_1;
    logic w_pass_2;
    logic w_active_2;
    logic w_fail_2;
    logic w_afired_2;

    // ── Child module instantiations (token-passing chain) ────────────────────
    sva_prop_afd80e6b_body_e0 u_sva_prop_afd80e6b_body_e0_0 (
        .clk(clk),
        .rst_n    (rst_n),
        .start    (start),
        .a(a),
        .disable_i     (disable_i),
        .active        (w_active_0),
        .pass          (w_pass_0),
        .fail          (w_fail_0),
        .attempt_fired (w_afired_0),
        .disabled_o    ()
    );
    sva_delay_1_1 u_sva_delay_1_1_1 (
        .clk(clk),
        .rst_n    (rst_n),
        .start    (w_pass_0),
        .disable_i     (disable_i),
        .active        (w_active_1),
        .pass          (w_pass_1),
        .fail          (w_fail_1),
        .attempt_fired (w_afired_1),
        .disabled_o    ()
    );
    sva_prop_afd80e6b_body_e1 u_sva_prop_afd80e6b_body_e1_2 (
        .clk(clk),
        .rst_n    (rst_n),
        .start    (w_pass_1),
        .b(b),
        .disable_i     (disable_i),
        .active        (w_active_2),
        .pass          (w_pass_2),
        .fail          (w_fail_2),
        .attempt_fired (w_afired_2),
        .disabled_o    ()
    );

    // ── Top-level output aggregation ─────────────────────────────────────────
    assign active = disable_i ? 1'b0 : (w_active_0 | w_active_1 | w_active_2);
    assign pass   = disable_i ? 1'b0 : w_pass_2;
    assign fail   = disable_i ? 1'b0 : (w_fail_0 | w_fail_1 | w_fail_2);
    assign attempt_fired = w_afired_0;
    assign disabled_o    = disable_i;

endmodule

// Generated by sva2rtl 1.3.1
// Source: first_match.sv:2:3
// Original property: @(posedge clk) first_match(a ##1 b)
module sva_prop_afd80e6b (
input  logic clk,
input  logic rst_n,
input  logic start,
input  logic a,
input  logic b,
input  logic disable_i,
output  logic active,
output  logic pass,
output  logic fail,
output  logic attempt_fired,
output  logic disabled_o
);

    // ── Body instance ─────────────────────────────────────────────────────────
    // Instantiate body checker: sva_prop_afd80e6b_body
    logic body_start_w;
    logic body_pass_w;
    logic body_fail_w;
    logic body_active_w;
    logic body_attempt_fired_w;
    logic body_disabled_o_w;

    sva_prop_afd80e6b_body #(
        .clock_signal(clk),        .clock_edge(posedge),    ) u_body (
        .clk  (clk),
        .rst_n      (rst_n),
        .start      (body_start_w),
        .a       (a),
        .b       (b),
        .disable_i  (disable_i),
        .active     (body_active_w),
        .pass       (body_pass_w),
        .fail       (body_fail_w),
        .attempt_fired (body_attempt_fired_w),
        .disabled_o    (body_disabled_o_w)
    );

    assign body_start_w = start;

    // ── HARDEN-01: attempt_fired_q never cleared by disable_i ──────────
    logic attempt_fired_q;
always_ff @(posedge clk) begin
        if (!rst_n) begin
            attempt_fired_q <= '0;
        end else if (start) begin
            attempt_fired_q <= 1'b1;  // sticky — never cleared by disable_i (HARDEN-01)
        end
    end

    // ── first_match: lock after earliest completion ───────────────────────────
    // Once the body passes, suppress all subsequent pass/fail/active outputs.
    logic locked_q;

always_ff @(posedge clk) begin
        if (!rst_n || disable_i) begin
            locked_q <= 1'b0;
        end else if (body_pass_w) begin
            locked_q <= 1'b1;
        end
    end

    // ── Output logic ──────────────────────────────────────────────────────────
    assign active        = disable_i ? 1'b0 : (body_active_w && !locked_q);
    assign pass          = disable_i ? 1'b0 : (body_pass_w && !locked_q);
    assign fail          = disable_i ? 1'b0 : (body_fail_w && !locked_q);
    assign attempt_fired = attempt_fired_q;
    assign disabled_o    = disable_i;

endmodule
