// Generated by sva2rtl 0.1.0
// Source: impl_nonoverlap.sv:2:14
// Original property: @(posedge clk) a |=> b
module sva_nonoverlap_check #(
    parameter BV_WIDTH = 1
) (
input  logic clk,
input  logic rst_n,
input  logic start,
input  logic a,
input  logic b,
input  logic disable_i,
output  logic active,
output  logic pass,
output  logic fail,
output  logic attempt_fired,
output  logic overflow_flag,
output  logic disabled_o
);
    // ── Internal wires from child modules ────────────────────────────────────
    logic ant_pass_w, ant_active_w, ant_fail_w, ant_afired_w;
    logic con_pass_w, con_active_w, con_fail_w, con_afired_w;
    logic con_start_w;
    assign con_start_w = bv_q[BV_WIDTH-1];

    // ── Child instantiations ─────────────────────────────────────────────────
    sva_nonoverlap_check_ant u_sva_nonoverlap_check_ant (
        .clk(clk), .rst_n(rst_n), .start(start),
        .a(a),
        .disable_i(disable_i), .active(ant_active_w), .pass(ant_pass_w),
        .fail(ant_fail_w), .attempt_fired(ant_afired_w), .disabled_o()
    );
    sva_nonoverlap_check_con u_sva_nonoverlap_check_con (
        .clk(clk), .rst_n(rst_n), .start(con_start_w),
        .b(b),
        .disable_i(disable_i), .active(con_active_w), .pass(con_pass_w),
        .fail(con_fail_w), .attempt_fired(con_afired_w), .disabled_o()
    );

    // ── Bit-vector shift register + delay for |=> ─────────────────────────────
    logic ant_pass_delayed_q;
    logic [BV_WIDTH-1:0] bv_q;
    logic overflow_flag_q;
    logic overflow_event;
    assign overflow_event = ant_pass_delayed_q && (&bv_q) && !overflow_flag_q;

always_ff @(posedge clk) begin
        if (!rst_n || disable_i) begin
            ant_pass_delayed_q <= 1'b0;
            bv_q               <= '0;
            overflow_flag_q    <= 1'b0;
        end else begin
            ant_pass_delayed_q <= ant_pass_w;
            if (overflow_flag_q) begin
                bv_q <= bv_q; overflow_flag_q <= 1'b1;
            end else begin
                overflow_flag_q <= overflow_flag_q | overflow_event;
                bv_q <= ant_pass_delayed_q;
            end
        end
    end

    // ── HARDEN-01: attempt_fired_q never cleared by disable_i ──────────
    logic attempt_fired_q;
always_ff @(posedge clk) begin
        if (!rst_n) begin
            attempt_fired_q <= '0;
        end else if (ant_pass_w) begin
            attempt_fired_q <= 1'b1;  // sticky — never cleared by disable_i (HARDEN-01)
        end
    end

    assign active        = disable_i ? 1'b0 : (overflow_flag_q ? 1'b0 : (ant_active_w | con_active_w | (|bv_q)));
    assign pass          = disable_i ? 1'b0 : (overflow_flag_q ? 1'b0 : (bv_q[BV_WIDTH-1] & con_pass_w));
    assign fail          = disable_i ? 1'b0 : (overflow_event ? 1'b1 :
                           overflow_flag_q ? 1'b0 : (bv_q[BV_WIDTH-1] & ~con_pass_w & con_start_w));
    assign attempt_fired = attempt_fired_q;
    assign overflow_flag = overflow_flag_q;
    assign disabled_o    = disable_i;
endmodule
