// Generated by sva2rtl 1.5.1
// Source: delay_three.sv:2:3
// Original property: @(posedge clk) ##2
module sva_delay_2_2 #(
    parameter CNT_WIDTH = 2
) (
input  logic clk,
input  logic rst_n,
input  logic start,
input  logic disable_i,
output  logic active,
output  logic pass,
output  logic fail,
output  logic attempt_fired,
output  logic disabled_o
);
    // ── Counter-based delay ──────────────────────────────────────────────────
    logic [CNT_WIDTH-1:0] count_q;
    logic                 running_q;

always_ff @(posedge clk) begin
        if (!rst_n || disable_i) begin
            count_q         <= '0;
            running_q       <= 1'b0;
        end else begin
            if (start) begin
                count_q   <= '0;
                running_q <= 1'b1;
            end else if (running_q) begin
                if (count_q == 2'd2) begin
                    running_q <= 1'b0;
                end else begin
                    count_q <= count_q + 1'b1;
                end
            end
        end
    end

    // ── HARDEN-01: attempt_fired_q never cleared by disable_i ──────────
    logic attempt_fired_q;

always_ff @(posedge clk) begin
        if (!rst_n) begin
            attempt_fired_q <= '0;
        end else if (start) begin
            attempt_fired_q <= 1'b1;  // sticky — never cleared by disable_i (HARDEN-01)
        end
    end

    assign active        = disable_i ? 1'b0 : running_q;
    assign pass          = disable_i ? 1'b0 : (
                               (start && (2 <= 1) && (2 >= 1))
                               || (running_q && (count_q >= 2'd0) && (count_q <= 2'd0))
                           );
    assign fail          = 1'b0;
    assign attempt_fired = attempt_fired_q;
    assign disabled_o    = disable_i;
endmodule
