// Generated by sva2rtl 0.1.0
// Source: delay_range.sv:2:3
// Original property: @(posedge clk) ##[2:5]
module sva_delay_2_5 #(
    parameter CNT_WIDTH = 3
) (
    input  logic clk,
    input  logic rst_n,
    input  logic start,
    output logic active,
    output logic pass,
    output logic fail,
    output logic attempt_fired
);
    // ── Counter-based delay ──────────────────────────────────────────────────
    logic [CNT_WIDTH-1:0] count_q;
    logic                 running_q;
    logic                 attempt_fired_q;

    always_ff @(posedge clk) begin
        if (!rst_n) begin
            count_q         <= '0;
            running_q       <= 1'b0;
            attempt_fired_q <= 1'b0;
        end else begin
            attempt_fired_q <= attempt_fired_q | start;  // sticky
            if (start) begin
                count_q   <= '0;
                running_q <= 1'b1;
            end else if (running_q) begin
                if (count_q == 3'd5) begin
                    running_q <= 1'b0;
                end else begin
                    count_q <= count_q + 1'b1;
                end
            end
        end
    end

    assign active        = running_q;
    assign pass          = running_q && (count_q >= 3'd2) && (count_q <= 3'd5);
    assign fail          = 1'b0;
    assign attempt_fired = attempt_fired_q;
endmodule
