// Generated by sva2rtl 1.5.2
// Source: nonconsec_rep.sv:2:3
// Original property: @(posedge clk) a [=5]
module sva_prop_7de9fe74 #(
    parameter CNT_WIDTH = 3
) (
input  logic clk,
input  logic rst_n,
input  logic start,
input  logic a,
input  logic disable_i,
output  logic active,
output  logic pass,
output  logic fail,
output  logic attempt_fired,
output  logic disabled_o
);
    // ── Signal evaluation ────────────────────────────────────────────────────
    logic sig_eval;
    assign sig_eval = (a);

    // ── Non-consecutive repetition [=N]: count occurrences, relaxed tail ─────
    // Counts non-consecutive sig=true cycles. Passes when count >= rep_min.
    // Unlike [->N], the expression can stay true after N matches.
    logic [CNT_WIDTH-1:0] count_q;
    logic running_q;
    logic passed_q;

    logic hit_now;
    assign hit_now = !passed_q && sig_eval &&
                     ((start && !running_q && (3'd5 == 3'd1)) ||
                      (running_q && (count_q >= (3'd5 - 3'd1))));

always_ff @(posedge clk) begin
        if (!rst_n || disable_i) begin
            count_q   <= '0;
            running_q <= 1'b0;
            passed_q  <= 1'b0;
        end else if (hit_now) begin
            running_q <= 1'b0;
            passed_q  <= 1'b1;
        end else if (start && !running_q && !passed_q) begin
            running_q <= 1'b1;
            count_q   <= sig_eval ? 3'd1 : '0;
        end else if (running_q && !passed_q) begin
            if (sig_eval && count_q < 3'd5)
                count_q <= count_q + 1'b1;
        end
    end

    // ── HARDEN-01 ────────────────────────────────────────────────────────────
    logic attempt_fired_q;
always_ff @(posedge clk) begin
        if (!rst_n) begin
            attempt_fired_q <= '0;
        end else if (start) begin
            attempt_fired_q <= 1'b1;  // sticky — never cleared by disable_i (HARDEN-01)
        end
    end

    // ── Output logic ──────────────────────────────────────────────────────────
    logic pass_internal;
    logic fail_internal;

    assign pass_internal = passed_q | hit_now;
    assign fail_internal = 1'b0;  // [=N] never fails, only waits

    assign active        = disable_i ? 1'b0 : ((start | running_q) & ~pass_internal);
    assign pass          = disable_i ? 1'b0 : pass_internal;
    assign fail          = disable_i ? 1'b0 : fail_internal;
    assign attempt_fired = attempt_fired_q;
    assign disabled_o    = disable_i;

endmodule
