// Generated by sva2rtl 1.5.0
// Source: until_ab.sv:2:3
// Original property: @(posedge clk) (a) until (b)
//
// Weak until: (a) until (b).  Safety FSM (no liveness obligation).
// Armed by `start`; evaluated each cycle from the start cycle (offset 0) onward:
//   PASS when b (a held at every prior cycle; b not required of a);
//   FAIL at the first cycle where ~b & ~a (a dropped before b became true).
// Registered outputs (1-cycle latency).  An undecided attempt stays pending
// (running) — faithful to the weak (no-liveness) semantics.
module sva_u_ab (
input  logic clk,
input  logic rst_n,
input  logic start,
input  logic a,
input  logic b,
input  logic disable_i,
output  logic active,
output  logic pass,
output  logic fail,
output  logic attempt_fired,
output  logic disabled_o
);
    // ── Operands (combinational) ───────────────────────────────────────
    logic a_result, b_result;
    assign a_result = (a);
    assign b_result = (b);

    logic running_q, pass_q, fail_q;

    // An attempt is live on the start cycle and while running_q holds.
    logic live, d_pass, d_fail, decided;
    assign live = start | running_q;
    assign d_pass = live &  b_result;
    assign d_fail = live & ~b_result & ~a_result;
    assign decided = d_pass | d_fail;

always_ff @(posedge clk) begin
        if (!rst_n || disable_i) begin
            running_q <= 1'b0;
            pass_q    <= 1'b0;
            fail_q    <= 1'b0;
        end else begin
            pass_q <= d_pass;
            fail_q <= d_fail;
            if (start) begin
                running_q <= ~decided;
            end else if (running_q && decided) begin
                running_q <= 1'b0;
            end
        end
    end
    assign active = disable_i ? 1'b0 : running_q;

    // ── HARDEN-01: attempt_fired_q never cleared by disable_i ──────────
    logic attempt_fired_q;
always_ff @(posedge clk) begin
        if (!rst_n) begin
            attempt_fired_q <= '0;
        end else if (start) begin
            attempt_fired_q <= 1'b1;  // sticky — never cleared by disable_i (HARDEN-01)
        end
    end

    assign pass          = disable_i ? 1'b0 : pass_q;
    assign fail          = disable_i ? 1'b0 : fail_q;
    assign attempt_fired = attempt_fired_q;
    assign disabled_o    = disable_i;
endmodule
