// Generated by sva2rtl 1.5.1
// Source: rep_fixed.sv:2:3
// Original property: @(posedge clk) a [*3]
module sva_prop_ed6835ae #(
    parameter CNT_WIDTH = 2
) (
input  logic clk,
input  logic rst_n,
input  logic start,
input  logic a,
input  logic disable_i,
output  logic active,
output  logic pass,
output  logic fail,
output  logic attempt_fired,
output  logic disabled_o
);
    // ── Signal evaluation ────────────────────────────────────────────────────
    logic sig_eval;
    assign sig_eval = (a);

    // ── Counter-based consecutive repetition FSM ─────────────────────────────
    logic [CNT_WIDTH-1:0] count_q;
    logic running_q;

always_ff @(posedge clk) begin
        if (!rst_n || disable_i) begin
            count_q   <= '0;
            running_q <= 1'b0;
        end else begin
            if (start && sig_eval) begin
                running_q <= 1'b1;
                count_q   <= 2'd1;
            end else if (running_q && sig_eval) begin
                if (count_q < 2'd3)
                    count_q <= count_q + 1'b1;
            end else if (running_q && !sig_eval) begin
                running_q <= 1'b0;
                count_q   <= '0;
            end
        end
    end

    // ── HARDEN-01: attempt_fired_q never cleared by disable_i ──────────
    logic attempt_fired_q;
always_ff @(posedge clk) begin
        if (!rst_n) begin
            attempt_fired_q <= '0;
        end else if (start) begin
            attempt_fired_q <= 1'b1;  // sticky — never cleared by disable_i (HARDEN-01)
        end
    end

    // ── Output logic ─────────────────────────────────────────────────────────
    logic pass_internal;
    logic fail_internal;
    logic active_internal;

    assign active_internal = running_q;
    assign pass_internal   = running_q && sig_eval &&
                             (count_q >= 2'd3) &&
                             (count_q <= 2'd3);
    assign fail_internal   = running_q && !sig_eval &&
                             (count_q < 2'd3);

    assign active        = disable_i ? 1'b0 : active_internal;
    assign pass          = disable_i ? 1'b0 : pass_internal;
    assign fail          = disable_i ? 1'b0 : fail_internal;
    assign attempt_fired = attempt_fired_q;
    assign disabled_o    = disable_i;
endmodule
