// Generated by sva2rtl 1.3.1
// Source: impl_bitvec.sv:2:14
// Original property: @(posedge clk) a |-> a ##[2:5] b
module sva_bitvec_impl #(
    parameter BV_WIDTH = 6
) (
input  logic clk,
input  logic rst_n,
input  logic start,
input  logic a,
input  logic b,
input  logic disable_i,
output  logic active,
output  logic pass,
output  logic fail,
output  logic attempt_fired,
output  logic overflow_flag,
output  logic disabled_o
);
    // ── Internal wires from child modules ────────────────────────────────────
    logic ant_pass_w;
    logic ant_active_w;
    logic ant_fail_w;
    logic ant_afired_w;
    logic con_pass_w;
    logic con_active_w;
    logic con_fail_w;
    logic con_afired_w;

    // ── Consequent start: driven from bit-vector oldest thread ────────────────
    logic con_start_w;
    assign con_start_w = bv_q[BV_WIDTH-1];

    // ── Antecedent child instantiation ───────────────────────────────────────
    sva_bitvec_impl_ant u_sva_bitvec_impl_ant (
        .clk(clk),
        .rst_n    (rst_n),
        .start    (start),
        .a(a),
        .disable_i     (disable_i),
        .active        (ant_active_w),
        .pass          (ant_pass_w),
        .fail          (ant_fail_w),
        .attempt_fired (ant_afired_w),
        .disabled_o    ()
    );

    // ── Consequent child instantiation ───────────────────────────────────────
    sva_bitvec_impl_con u_sva_bitvec_impl_con (
        .clk(clk),
        .rst_n    (rst_n),
        .start    (con_start_w),
        .a(a),
        .b(b),
        .disable_i     (disable_i),
        .active        (con_active_w),
        .pass          (con_pass_w),
        .fail          (con_fail_w),
        .attempt_fired (con_afired_w),
        .disabled_o    ()
    );

    // ── Bit-vector shift register (thread tracker) ────────────────────────────
    logic [BV_WIDTH-1:0] bv_q;
    logic                overflow_flag_q;

    logic overflow_event;
    assign overflow_event = ant_pass_w && (&bv_q) && !overflow_flag_q;

always_ff @(posedge clk) begin
        if (!rst_n || disable_i) begin
            bv_q            <= '0;
            overflow_flag_q <= 1'b0;
        end else begin
            if (overflow_flag_q) begin
                bv_q            <= bv_q;
                overflow_flag_q <= 1'b1;
            end else begin
                overflow_flag_q <= overflow_flag_q | overflow_event;
                bv_q <= {ant_pass_w, bv_q[BV_WIDTH-1:1]};
            end
        end
    end

    // ── HARDEN-01: attempt_fired_q never cleared by disable_i ──────────
    logic attempt_fired_q;

always_ff @(posedge clk) begin
        if (!rst_n) begin
            attempt_fired_q <= '0;
        end else if (ant_pass_w) begin
            attempt_fired_q <= 1'b1;  // sticky — never cleared by disable_i (HARDEN-01)
        end
    end

    // ── Output assignments ────────────────────────────────────────────────────
    assign active        = disable_i ? 1'b0 : (overflow_flag_q ? 1'b0 : (ant_active_w | con_active_w | (|bv_q)));
    assign pass          = disable_i ? 1'b0 : (overflow_flag_q ? 1'b0 : (bv_q[BV_WIDTH-1] & con_pass_w));
    assign fail          = disable_i ? 1'b0 : (overflow_event  ? 1'b1 :
                           overflow_flag_q ? 1'b0 :
                           (bv_q[BV_WIDTH-1] & ~con_pass_w & con_start_w));
    assign attempt_fired = attempt_fired_q;
    assign overflow_flag = overflow_flag_q;
    assign disabled_o    = disable_i;

endmodule
