// Generated by sva2rtl 1.5.1
// Source: rose.sv:2:3
// Original property: @(posedge clk) $rose(sig)
module sva_prop_d9858ddb (
input  logic clk,
input  logic rst_n,
input  logic start,
input  logic sig,
input  logic disable_i,
output  logic active,
output  logic pass,
output  logic fail,
output  logic attempt_fired,
output  logic disabled_o
);

    // ── Edge-detect registers ─────────────────────────────────────────────────
    logic sig_prev_q;

always_ff @(posedge clk) begin
        if (!rst_n || disable_i) begin
            sig_prev_q      <= 1'b0;
        end else begin
            sig_prev_q      <= sig;
        end
    end

    // ── HARDEN-01: attempt_fired_q never cleared by disable_i ──────────
    logic attempt_fired_q;

always_ff @(posedge clk) begin
        if (!rst_n) begin
            attempt_fired_q <= '0;
        end else if (start) begin
            attempt_fired_q <= 1'b1;  // sticky — never cleared by disable_i (HARDEN-01)
        end
    end

    // ── Detection logic ───────────────────────────────────────────────────────
    // $rose: 0->1 transition on previous-to-current clock edge
    logic rose_detect;
    assign rose_detect = sig & ~sig_prev_q;

    // ── Output logic ──────────────────────────────────────────────────────────
    logic pass_internal;
    logic fail_internal;

    assign pass_internal = start & rose_detect;
    assign fail_internal = start & ~rose_detect;

    assign active        = disable_i ? 1'b0 : start;
    assign pass          = disable_i ? 1'b0 : pass_internal;
    assign fail          = disable_i ? 1'b0 : fail_internal;
    assign attempt_fired = attempt_fired_q;
    assign disabled_o    = disable_i;

endmodule
