// Generated by sva2rtl 1.4.0
// Source: delay_range.sv:2:42
// Original property: @(posedge clk) a ##[2:5] b
module sva_prop_e9edaa37_e1 (
input  logic clk,
input  logic rst_n,
input  logic start,
input  logic b,
input  logic disable_i,
output  logic active,
output  logic pass,
output  logic fail,
output  logic attempt_fired,
output  logic disabled_o
);

    // ── Combinational evaluation ───────────────────────────────────────
    logic bool_result;
    assign bool_result = (b);

    // ── Registered outputs (OUT-02: no combinational glitches) ─────────
    logic active_q, pass_q, fail_q;

always_ff @(posedge clk) begin
        if (!rst_n || disable_i) begin
            active_q <= 1'b0;
            pass_q   <= 1'b0;
            fail_q   <= 1'b0;
        end else begin
            active_q <= start;
            pass_q   <= start &  bool_result;
            fail_q   <= start & ~bool_result;
        end
    end

    // ── HARDEN-01: attempt_fired_q never cleared by disable_i ──────────
    logic attempt_fired_q;

always_ff @(posedge clk) begin
        if (!rst_n) begin
            attempt_fired_q <= '0;
        end else if (start) begin
            attempt_fired_q <= 1'b1;  // sticky — never cleared by disable_i (HARDEN-01)
        end
    end

    assign active        = disable_i ? 1'b0 : active_q;
    assign pass          = disable_i ? 1'b0 : pass_q;
    assign fail          = disable_i ? 1'b0 : fail_q;
    assign attempt_fired = attempt_fired_q;
    assign disabled_o    = disable_i;

endmodule
