// Generated by sva2rtl 1.4.1
// Source: always_1_3.sv:2:3
// Original property: @(posedge clk) always [1:3] (a)
//
// Bounded always: always [1:3] (p).  Armed by `start` (offset 0).
// The UNIVERSAL dual of s_eventually: the operand must hold at EVERY in-window
// offset (lo<=k<=hi).  FAIL at start + k_viol + 1 where k_viol is the first
// in-window offset at which the operand is false; PASS at start + 3 + 1 if
// every in-window cycle holds.  Registered outputs (1-cycle latency).
module sva_sa_1_3 #(
    parameter CNT_WIDTH = 2
) (
input  logic clk,
input  logic rst_n,
input  logic start,
input  logic a,
input  logic disable_i,
output  logic active,
output  logic pass,
output  logic fail,
output  logic attempt_fired,
output  logic disabled_o
);
    // ── Operand (combinational) ────────────────────────────────────────
    logic bool_result;
    assign bool_result = (a);

    logic pass_q, fail_q;
    logic [CNT_WIDTH-1:0] cnt_q;
    logic                 running_q, viol_q;

    // Window misses: offset 0 at the start cycle; offset k>=1 when cnt_q == k-1.
    logic miss0, missk, miss_now, end_now;
    assign miss0   = 1'b0;
    assign missk   = running_q & ~bool_result & (cnt_q <= 2'd2) & ~viol_q;
    assign miss_now = miss0 | missk;
    assign end_now = running_q & (cnt_q == 2'd2);

always_ff @(posedge clk) begin
        if (!rst_n || disable_i) begin
            cnt_q     <= '0;
            running_q <= 1'b0;
            viol_q    <= 1'b0;
            pass_q    <= 1'b0;
            fail_q    <= 1'b0;
        end else begin
            if (start) begin
                cnt_q     <= '0;
                running_q <= 1'b1;
                viol_q    <= miss0;
                fail_q    <= miss0;
                pass_q    <= 1'b0;
            end else begin
                fail_q <= missk;
                pass_q <= end_now & ~viol_q & ~miss_now;
                viol_q <= viol_q | missk;
                if (running_q) begin
                    if (cnt_q == 2'd2) begin
                        running_q <= 1'b0;
                    end else begin
                        cnt_q <= cnt_q + 1'b1;
                    end
                end
            end
        end
    end
    assign active = disable_i ? 1'b0 : running_q;

    // ── HARDEN-01: attempt_fired_q never cleared by disable_i ──────────
    logic attempt_fired_q;
always_ff @(posedge clk) begin
        if (!rst_n) begin
            attempt_fired_q <= '0;
        end else if (start) begin
            attempt_fired_q <= 1'b1;  // sticky — never cleared by disable_i (HARDEN-01)
        end
    end

    assign pass          = disable_i ? 1'b0 : pass_q;
    assign fail          = disable_i ? 1'b0 : fail_q;
    assign attempt_fired = attempt_fired_q;
    assign disabled_o    = disable_i;
endmodule
