// Generated by sva2rtl 1.4.0
// Source: impl_nonoverlap.sv:2:14
// Original property: @(posedge clk) a |=> b
module sva_nonoverlap_check #(
    parameter BV_WIDTH = 1
) (
input  logic clk,
input  logic rst_n,
input  logic start,
input  logic a,
input  logic b,
input  logic disable_i,
output  logic active,
output  logic pass,
output  logic fail,
output  logic attempt_fired,
output  logic overflow_flag,
output  logic disabled_o
);
    // ── Internal wires from child modules ────────────────────────────────────
    logic ant_pass_w, ant_active_w, ant_fail_w, ant_afired_w;
    logic con_pass_w, con_active_w, con_fail_w, con_afired_w;
    logic con_start_w;
    // BUG-IMPL-01 fix: single-cycle (boolean / sampled-value) consequent.
    // Start the consequent leaf exactly when the antecedent matches
    // (con_start = ant_pass_w).  Because the consequent leaf samples its operand
    // on its own start cycle, this checks `b` exactly one cycle after `a` — the
    // ##1 of |=> — and works for both continuous (start≡1) and pulsed/composed
    // start.  con_pass_w / con_fail_w then carry the fully-aligned verdict, so
    // no bv_q thread tracker or extra gate is needed.  Formally proven
    // equivalent to IEEE-1800 |=> (see tests/test_formal_sva_equiv).  The
    // previous bv_q-gated con_start mis-timed b by two cycles and the
    // bv_q[MSB] gate dropped valid passes / raised spurious fails.
    assign con_start_w = ant_pass_w;

    // ── Child instantiations ─────────────────────────────────────────────────
    sva_nonoverlap_check_ant u_sva_nonoverlap_check_ant (
        .clk(clk), .rst_n(rst_n), .start(start),
        .a(a),
        .disable_i(disable_i), .active(ant_active_w), .pass(ant_pass_w),
        .fail(ant_fail_w), .attempt_fired(ant_afired_w), .disabled_o()
    );
    sva_nonoverlap_check_con u_sva_nonoverlap_check_con (
        .clk(clk), .rst_n(rst_n), .start(con_start_w),
        .b(b),
        .disable_i(disable_i), .active(con_active_w), .pass(con_pass_w),
        .fail(con_fail_w), .attempt_fired(con_afired_w), .disabled_o()
    );

    // ── HARDEN-01: attempt_fired_q never cleared by disable_i ──────────
    logic attempt_fired_q;
always_ff @(posedge clk) begin
        if (!rst_n) begin
            attempt_fired_q <= '0;
        end else if (ant_pass_w) begin
            attempt_fired_q <= 1'b1;  // sticky — never cleared by disable_i (HARDEN-01)
        end
    end

    // ── Output assignments (|=> single-cycle consequent) ──────────────────────
    // con_start_w = ant_pass_w, so con_pass_w / con_fail_w already encode
    // "antecedent matched AND b held/failed one cycle later" — the |=> verdict.
    assign active        = disable_i ? 1'b0 : (ant_active_w | con_active_w);
    assign pass          = disable_i ? 1'b0 : con_pass_w;
    assign fail          = disable_i ? 1'b0 : con_fail_w;
    assign attempt_fired = attempt_fired_q;
    assign overflow_flag = 1'b0;
    assign disabled_o    = disable_i;
endmodule
