// Generated by sva2rtl 1.3.0
// Source: past.sv:2:3
// Original property: @(posedge clk) $past(sig, 3)
module sva_prop_a9da8230 #(
    parameter DEPTH = 3
) (
input  logic clk,
input  logic rst_n,
input  logic start,
input  logic sig,
input  logic disable_i,
output  logic active,
output  logic pass,
output  logic fail,
output  logic attempt_fired,
output  logic disabled_o
);

    // ── Shift-register pipeline (DEPTH stages = $past(sig, DEPTH)) ────────────

    // Multi-FF shift register for DEPTH > 1
    logic [DEPTH-1:0] shift_q;

always_ff @(posedge clk) begin
        if (!rst_n || disable_i) begin
            shift_q         <= '0;
        end else begin
            shift_q         <= {shift_q[DEPTH-2:0], sig};
        end
    end

    logic past_value;
    assign past_value = shift_q[DEPTH-1];


    // ── HARDEN-01: attempt_fired_q never cleared by disable_i ──────────
    logic attempt_fired_q;

always_ff @(posedge clk) begin
        if (!rst_n) begin
            attempt_fired_q <= '0;
        end else if (start) begin
            attempt_fired_q <= 1'b1;  // sticky — never cleared by disable_i (HARDEN-01)
        end
    end

    // ── Output logic ──────────────────────────────────────────────────────────
    logic pass_internal;
    logic fail_internal;

    assign pass_internal = start & past_value;
    assign fail_internal = start & ~past_value;

    assign active        = disable_i ? 1'b0 : start;
    assign pass          = disable_i ? 1'b0 : pass_internal;
    assign fail          = disable_i ? 1'b0 : fail_internal;
    assign attempt_fired = attempt_fired_q;
    assign disabled_o    = disable_i;

endmodule
