// Generated by sva2rtl 0.1.0
// Source: delay_three.sv:2:3
// Original property: @(posedge clk) a ##1 b ##2 c
module sva_prop_5c9caf75 (
input  logic clk,
input  logic rst_n,
input  logic start,
input  logic a,
input  logic b,
input  logic c,
input  logic disable_i,
output  logic active,
output  logic pass,
output  logic fail,
output  logic attempt_fired,
output  logic disabled_o
);
    // ── Internal token wires (N+1 wires for N children) ─────────────────────
    logic w_pass_0;
    logic w_active_0;
    logic w_fail_0;
    logic w_afired_0;
    logic w_pass_1;
    logic w_active_1;
    logic w_fail_1;
    logic w_afired_1;
    logic w_pass_2;
    logic w_active_2;
    logic w_fail_2;
    logic w_afired_2;
    logic w_pass_3;
    logic w_active_3;
    logic w_fail_3;
    logic w_afired_3;
    logic w_pass_4;
    logic w_active_4;
    logic w_fail_4;
    logic w_afired_4;

    // ── Child module instantiations (token-passing chain) ────────────────────
    sva_prop_5c9caf75_e0 u_sva_prop_5c9caf75_e0_0 (
        .clk(clk),
        .rst_n    (rst_n),
        .start    (start),
        .a(a),
        .disable_i     (disable_i),
        .active        (w_active_0),
        .pass          (w_pass_0),
        .fail          (w_fail_0),
        .attempt_fired (w_afired_0),
        .disabled_o    ()
    );
    sva_delay_1_1 u_sva_delay_1_1_1 (
        .clk(clk),
        .rst_n    (rst_n),
        .start    (w_pass_0),
        .disable_i     (disable_i),
        .active        (w_active_1),
        .pass          (w_pass_1),
        .fail          (w_fail_1),
        .attempt_fired (w_afired_1),
        .disabled_o    ()
    );
    sva_prop_5c9caf75_e1 u_sva_prop_5c9caf75_e1_2 (
        .clk(clk),
        .rst_n    (rst_n),
        .start    (w_pass_1),
        .b(b),
        .disable_i     (disable_i),
        .active        (w_active_2),
        .pass          (w_pass_2),
        .fail          (w_fail_2),
        .attempt_fired (w_afired_2),
        .disabled_o    ()
    );
    sva_delay_2_2 u_sva_delay_2_2_3 (
        .clk(clk),
        .rst_n    (rst_n),
        .start    (w_pass_2),
        .disable_i     (disable_i),
        .active        (w_active_3),
        .pass          (w_pass_3),
        .fail          (w_fail_3),
        .attempt_fired (w_afired_3),
        .disabled_o    ()
    );
    sva_prop_5c9caf75_e2 u_sva_prop_5c9caf75_e2_4 (
        .clk(clk),
        .rst_n    (rst_n),
        .start    (w_pass_3),
        .c(c),
        .disable_i     (disable_i),
        .active        (w_active_4),
        .pass          (w_pass_4),
        .fail          (w_fail_4),
        .attempt_fired (w_afired_4),
        .disabled_o    ()
    );

    // ── Top-level output aggregation ─────────────────────────────────────────
    assign active = disable_i ? 1'b0 : (w_active_0 | w_active_1 | w_active_2 | w_active_3 | w_active_4);
    assign pass   = disable_i ? 1'b0 : w_pass_4;
    assign fail   = disable_i ? 1'b0 : (w_fail_0 | w_fail_1 | w_fail_2 | w_fail_3 | w_fail_4);
    assign attempt_fired = w_afired_0;
    assign disabled_o    = disable_i;

endmodule
