// Generated by sva2rtl 1.4.0
// Source: disable_iff_test.sv:2:3
// Original property: @(posedge clk) disable iff ((!rst_n)) a |-> b
module sva_prop_7ad1ea48_body #(
    parameter BV_WIDTH = 1
) (
input  logic clk,
input  logic rst_n,
input  logic start,
input  logic a,
input  logic b,
input  logic disable_i,
output  logic active,
output  logic pass,
output  logic fail,
output  logic attempt_fired,
output  logic overflow_flag,
output  logic disabled_o
);
    // ── Internal wires from child modules ────────────────────────────────────
    logic ant_pass_w;
    logic ant_active_w;
    logic ant_fail_w;
    logic ant_afired_w;
    logic con_pass_w;
    logic con_active_w;
    logic con_fail_w;
    logic con_afired_w;

    // ── Consequent start ──────────────────────────────────────────────────────
    logic con_start_w;
    // BUG-IMPL-01 fix: single-cycle (boolean / sampled-value) consequent.
    // Evaluate the consequent leaf IN PARALLEL with the antecedent
    // (con_start = start) so a and b are sampled on the same cycle, matching
    // IEEE-1800 |-> semantics.  Formally proven equivalent (see
    // test_formal_sva_equiv).  The previous bv_q-gated con_start mis-timed b by
    // two cycles and the gate dropped valid passes / raised spurious fails for
    // non-continuous antecedents.
    assign con_start_w = start;

    // ── Antecedent child instantiation ───────────────────────────────────────
    sva_prop_7ad1ea48_body_ant u_sva_prop_7ad1ea48_body_ant (
        .clk(clk),
        .rst_n    (rst_n),
        .start    (start),
        .a(a),
        .disable_i     (disable_i),
        .active        (ant_active_w),
        .pass          (ant_pass_w),
        .fail          (ant_fail_w),
        .attempt_fired (ant_afired_w),
        .disabled_o    ()
    );

    // ── Consequent child instantiation ───────────────────────────────────────
    sva_prop_7ad1ea48_body_con u_sva_prop_7ad1ea48_body_con (
        .clk(clk),
        .rst_n    (rst_n),
        .start    (con_start_w),
        .b(b),
        .disable_i     (disable_i),
        .active        (con_active_w),
        .pass          (con_pass_w),
        .fail          (con_fail_w),
        .attempt_fired (con_afired_w),
        .disabled_o    ()
    );

    // ── HARDEN-01: attempt_fired_q never cleared by disable_i ──────────
    logic attempt_fired_q;

always_ff @(posedge clk) begin
        if (!rst_n) begin
            attempt_fired_q <= '0;
        end else if (ant_pass_w) begin
            attempt_fired_q <= 1'b1;  // sticky — never cleared by disable_i (HARDEN-01)
        end
    end

    // ── Output assignments (|-> single-cycle consequent) ──────────────────────
    // ant_pass_w and con_pass_w are both registered one cycle by their leaves,
    // so combining them at the same cycle pairs a(t) with b(t) — overlapping
    // implication semantics.
    assign active        = disable_i ? 1'b0 : (ant_active_w | con_active_w);
    assign pass          = disable_i ? 1'b0 : (ant_pass_w & con_pass_w);
    assign fail          = disable_i ? 1'b0 : (ant_pass_w & con_fail_w);
    assign attempt_fired = attempt_fired_q;
    assign overflow_flag = 1'b0;
    assign disabled_o    = disable_i;

endmodule
