// Generated by sva2rtl 1.3.0
// Source: impl_bitvec.sv:2:48
// Original property: @(posedge clk) a |-> a ##[2:5] b
module sva_bitvec_impl_con (
input  logic clk,
input  logic rst_n,
input  logic start,
input  logic a,
input  logic b,
input  logic disable_i,
output  logic active,
output  logic pass,
output  logic fail,
output  logic attempt_fired,
output  logic disabled_o
);
    // ── Internal token wires (N+1 wires for N children) ─────────────────────
    logic w_pass_0;
    logic w_active_0;
    logic w_fail_0;
    logic w_afired_0;
    logic w_pass_1;
    logic w_active_1;
    logic w_fail_1;
    logic w_afired_1;
    logic w_pass_2;
    logic w_active_2;
    logic w_fail_2;
    logic w_afired_2;

    // ── Child module instantiations (token-passing chain) ────────────────────
    sva_bitvec_impl_con_e0 u_sva_bitvec_impl_con_e0_0 (
        .clk(clk),
        .rst_n    (rst_n),
        .start    (start),
        .a(a),
        .disable_i     (disable_i),
        .active        (w_active_0),
        .pass          (w_pass_0),
        .fail          (w_fail_0),
        .attempt_fired (w_afired_0),
        .disabled_o    ()
    );
    sva_delay_2_5 u_sva_delay_2_5_1 (
        .clk(clk),
        .rst_n    (rst_n),
        .start    (w_pass_0),
        .disable_i     (disable_i),
        .active        (w_active_1),
        .pass          (w_pass_1),
        .fail          (w_fail_1),
        .attempt_fired (w_afired_1),
        .disabled_o    ()
    );
    sva_bitvec_impl_con_e1 u_sva_bitvec_impl_con_e1_2 (
        .clk(clk),
        .rst_n    (rst_n),
        .start    (w_pass_1),
        .b(b),
        .disable_i     (disable_i),
        .active        (w_active_2),
        .pass          (w_pass_2),
        .fail          (w_fail_2),
        .attempt_fired (w_afired_2),
        .disabled_o    ()
    );

    // ── Top-level output aggregation ─────────────────────────────────────────
    assign active = disable_i ? 1'b0 : (w_active_0 | w_active_1 | w_active_2);
    assign pass   = disable_i ? 1'b0 : w_pass_2;
    assign fail   = disable_i ? 1'b0 : (w_fail_0 | w_fail_1 | w_fail_2);
    assign attempt_fired = w_afired_0;
    assign disabled_o    = disable_i;

endmodule
