// Generated by sva2rtl 1.7.1
// Source: s_eventually_1_3.sv:2:3
// Original property: @(posedge clk) s_eventually [1:3] (a)
//
// Bounded eventually: s_eventually [1:3] (p).  Armed by `start`
// (offset 0).  PASS at start + k* + 1 where k* is the first in-window offset
// (lo<=k<=hi) at which the operand holds; FAIL at start + 3 + 1 if the
// window closes with no holding cycle.  Registered outputs (1-cycle latency).
module sva_se_1_3 #(
    parameter CNT_WIDTH = 2
) (
input  logic clk,
input  logic rst_n,
input  logic start,
input  logic a,
input  logic disable_i,
output  logic active,
output  logic pass,
output  logic fail,
output  logic attempt_fired,
output  logic disabled_o
);
    // ── Operand (combinational) ────────────────────────────────────────
    logic bool_result;
    assign bool_result = (a);

    logic pass_q, fail_q;
    logic [CNT_WIDTH-1:0] cnt_q;
    logic                 running_q, sat_q;

    // Window hits: offset 0 at the start cycle; offset k>=1 when cnt_q == k-1.
    logic hit0, hitk, hit_now, end_now;
    assign hit0    = 1'b0;
    assign hitk    = running_q & bool_result & (cnt_q <= 2'd2) & ~sat_q;
    assign hit_now = hit0 | hitk;
    assign end_now = running_q & (cnt_q == 2'd2);

always_ff @(posedge clk) begin
        if (!rst_n || disable_i) begin
            cnt_q     <= '0;
            running_q <= 1'b0;
            sat_q     <= 1'b0;
            pass_q    <= 1'b0;
            fail_q    <= 1'b0;
        end else begin
            if (start) begin
                cnt_q     <= '0;
                running_q <= 1'b1;
                sat_q     <= hit0;
                pass_q    <= hit0;
                fail_q    <= 1'b0;
            end else begin
                pass_q <= hitk;
                fail_q <= end_now & ~sat_q & ~hit_now;
                sat_q  <= sat_q | hitk;
                if (running_q) begin
                    if (cnt_q == 2'd2) begin
                        running_q <= 1'b0;
                    end else begin
                        cnt_q <= cnt_q + 1'b1;
                    end
                end
            end
        end
    end
    assign active = disable_i ? 1'b0 : running_q;

    // ── HARDEN-01: attempt_fired_q never cleared by disable_i ──────────
    logic attempt_fired_q;
always_ff @(posedge clk) begin
        if (!rst_n) begin
            attempt_fired_q <= '0;
        end else if (start) begin
            attempt_fired_q <= 1'b1;  // sticky — never cleared by disable_i (HARDEN-01)
        end
    end

    assign pass          = disable_i ? 1'b0 : pass_q;
    assign fail          = disable_i ? 1'b0 : fail_q;
    assign attempt_fired = attempt_fired_q;
    assign disabled_o    = disable_i;
endmodule
