// Generated by sva2rtl 1.5.0
// Source: disable_iff_test.sv:2:3
// Original property: @(posedge clk) disable iff ((!rst_n)) a |-> b
module sva_prop_7ad1ea48 (
input  logic clk,
input  logic rst_n,
input  logic start,
input  logic a,
input  logic b,
input  logic disable_i,
output  logic active,
output  logic pass,
output  logic fail,
output  logic attempt_fired,
output  logic disabled_o
);
    // ── Combinational disable condition ───────────────────────────────────────
    logic cond_result;
    assign cond_result = ((!rst_n));

    // ── Effective disable: local condition OR incoming disable_i ─────────────
    logic effective_disable;
    assign effective_disable = disable_i | cond_result;

    // ── Body checker instantiation ────────────────────────────────────────────
    sva_prop_7ad1ea48_body u_sva_prop_7ad1ea48_body (
        .clk(clk),
        .rst_n    (rst_n),
        .start    (start),
        .a(a),
        .b(b),
        .disable_i     (effective_disable),
        .active        (active),
        .pass          (pass),
        .fail          (fail),
        .attempt_fired (attempt_fired),
        .disabled_o    ()
    );

    assign disabled_o = disable_i;

endmodule
